### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by shiraji** [shiraji/breakpoints-manager#1]
Need following feature before releasing this plugin
- [x] import/export breakpoints
- [x] Settings for saving/deleting breakpoints
- [x] Settings for sharing breakpoints to project
- [x] UI
- [x] Workspace <-> project config
- [x] Apply both single breakpoint with multiple select
- [x] Validation for unique name
- [x] Apply sets and single breakpoints
- [x] Rename entities
- [x] Show the breakpoints set is shared or not
- [x] Unique name? who care?
- [x] Remove empty breakpoints set
- [x] Clean up commits
- [x] Add .travis scripts
- [x] Add README

**Comment by shiraji** [comment]
done!
